import {
  AUTH_MANAGEMENT_PERMISSION_CODES,
  AUTH_SESSION_PERMISSION_CODES,
  COLLABORATION_TASK_PERMISSION_CODES,
  BROWSER_ACTIVITY_AUDIT_PERMISSION_CODES,
  CRM_MANAGEMENT_PERMISSION_CODES,
  HR_MANAGEMENT_PERMISSION_CODES,
  IDENTITY_ACCOUNT_PERMISSION_CODES,
  IDENTITY_ACCOUNT_SELF_PERMISSION_CODES,
  IDENTITY_MACHINE_PERMISSION_CODES,
  ITEM_MASTER_MANAGEMENT_PERMISSION_CODES,
  MES_MANAGEMENT_PERMISSION_CODES,
  PERMISSION_CODE_SEED_ITEMS,
  PERMISSION_MANAGEMENT_PERMISSION_CODES,
  PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES,
  PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES,
  ROLE_INSTANCE_PERMISSION_CODES,
  ROLE_TEMPLATE_PERMISSION_CODES,
  SITE_MANAGEMENT_PERMISSION_CODES,
  TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES,
  TENANT_ORG_MANAGEMENT_PERMISSION_CODES
} from './permission-catalog'
import { RoleKind, type RoleKind as RoleKindValue } from '../../prisma/generated/prisma'

export interface BuiltInRoleSeed {
  code: string
  description: string
  id: string
  isEnabled: boolean
  isProtected: boolean
  allowTenantPermissionOverride: boolean
  kind: RoleKindValue
  name: string
  permissionCodes: string[]
  scopeKey: string
  templateRoleCode: string | null
  tenantId: string | null
}

export type BuiltInSystemRoleSeed = BuiltInRoleSeed

export type BuiltInRoleTemplateSeed = BuiltInRoleSeed

// Publishes system-scope built-in role instances that platform environments should always be able to bootstrap.
export const BUILT_IN_SYSTEM_ROLES: BuiltInSystemRoleSeed[] = [
  {
    id: '37e76049-6d90-456c-8ded-2cc42c60f001',
    code: 'system.admin',
    name: '系统管理员',
    description: 'Built-in system administrator role for platform-level governance.',
    allowTenantPermissionOverride: false,
    isEnabled: true,
    isProtected: true,
    kind: RoleKind.SYSTEM_INSTANCE,
    scopeKey: '__SYSTEM__',
    templateRoleCode: null,
    tenantId: null,
    permissionCodes: [
      PERMISSION_MANAGEMENT_PERMISSION_CODES.CREATE_PERMISSION,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.UPDATE_PERMISSION,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.DELETE_PERMISSION,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_PERMISSION,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_PERMISSION_DETAIL,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_PERMISSION_DETAIL_BY_CODE,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_AUDIT_EVENT,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_NAVIGATION_ENTRY,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_NAVIGATION_ENTRY_DETAIL,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.CREATE_NAVIGATION_ENTRY,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.UPDATE_NAVIGATION_ENTRY,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.RESOLVE_NAVIGATION_PREVIEW,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_TERMINAL_ACCESS,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.MANAGE_ROLE_TERMINAL_ACCESS,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.MANAGE_ACCOUNT_TERMINAL_ACCESS,
      ROLE_TEMPLATE_PERMISSION_CODES.CREATE,
      ROLE_TEMPLATE_PERMISSION_CODES.UPDATE,
      ROLE_TEMPLATE_PERMISSION_CODES.DELETE,
      ROLE_TEMPLATE_PERMISSION_CODES.ASSIGN_PERMISSIONS,
      ROLE_TEMPLATE_PERMISSION_CODES.LIST,
      ROLE_TEMPLATE_PERMISSION_CODES.GET_BY_ID,
      ROLE_INSTANCE_PERMISSION_CODES.CREATE,
      ROLE_INSTANCE_PERMISSION_CODES.CREATE_FROM_TEMPLATE,
      ROLE_INSTANCE_PERMISSION_CODES.UPDATE,
      ROLE_INSTANCE_PERMISSION_CODES.DELETE,
      ROLE_INSTANCE_PERMISSION_CODES.ASSIGN_PERMISSIONS,
      ROLE_INSTANCE_PERMISSION_CODES.SYNC_FROM_TEMPLATE,
      ROLE_INSTANCE_PERMISSION_CODES.LIST,
      ROLE_INSTANCE_PERMISSION_CODES.GET_BY_ID,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.ASSIGN_ACCOUNT_ROLE,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_ACCOUNT_ROLE,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.CREATE_POLICY,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.UPDATE_POLICY,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_POLICY,
      AUTH_SESSION_PERMISSION_CODES.ADMIN_VIEW_USER_SESSIONS,
      AUTH_SESSION_PERMISSION_CODES.ADMIN_REVOKE_SESSION,
      AUTH_MANAGEMENT_PERMISSION_CODES.VIEW_AUDIT_EVENT,
      AUTH_MANAGEMENT_PERMISSION_CODES.BOOTSTRAP_ACCOUNT_CREDENTIALS,
      AUTH_MANAGEMENT_PERMISSION_CODES.MANAGE_ACCOUNT_LOGIN_METHODS,
      AUTH_MANAGEMENT_PERMISSION_CODES.MANAGE_PLATFORM_MFA_POLICY,
      IDENTITY_ACCOUNT_PERMISSION_CODES.LIST_ACCOUNT,
      IDENTITY_ACCOUNT_PERMISSION_CODES.CREATE_ACCOUNT,
      IDENTITY_ACCOUNT_PERMISSION_CODES.UPDATE_ACCOUNT_PROFILE,
      IDENTITY_ACCOUNT_PERMISSION_CODES.UPDATE_ACCOUNT_STATUS,
      IDENTITY_ACCOUNT_PERMISSION_CODES.DELETE_ACCOUNT,
      IDENTITY_ACCOUNT_SELF_PERMISSION_CODES.READ,
      IDENTITY_MACHINE_PERMISSION_CODES.CREATE_SERVICE_ACCOUNT,
      IDENTITY_MACHINE_PERMISSION_CODES.UPDATE_SERVICE_ACCOUNT_STATUS,
      IDENTITY_MACHINE_PERMISSION_CODES.CREATE_API_KEY,
      IDENTITY_MACHINE_PERMISSION_CODES.REVOKE_API_KEY,
      IDENTITY_MACHINE_PERMISSION_CODES.ROTATE_API_KEY,
      TENANT_ORG_MANAGEMENT_PERMISSION_CODES.LIST_TENANT,
      TENANT_ORG_MANAGEMENT_PERMISSION_CODES.VIEW_TENANT_DETAIL,
      TENANT_ORG_MANAGEMENT_PERMISSION_CODES.CREATE_TENANT,
      TENANT_ORG_MANAGEMENT_PERMISSION_CODES.UPDATE_TENANT_PROFILE,
      TENANT_ORG_MANAGEMENT_PERMISSION_CODES.UPDATE_TENANT_STATUS,
      TENANT_ORG_MANAGEMENT_PERMISSION_CODES.LIST_ORG_TREE,
      TENANT_ORG_MANAGEMENT_PERMISSION_CODES.VIEW_ORG_UNIT_DETAIL,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.CREATE_ENROLLMENT,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.REVOKE_ENROLLMENT,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.READ_DEVICE,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.READ_SENSITIVE_DEVICE,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.DISABLE_DEVICE,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.MARK_LOST_DEVICE,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.MARK_MAINTENANCE_DEVICE,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.RESTORE_ACTIVE_DEVICE,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.MANAGE_VERSION_POLICY,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.READ_AUDIT,
      CRM_MANAGEMENT_PERMISSION_CODES.READ_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.CREATE_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.UPDATE_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.CONVERT_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.CLAIM_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.RELEASE_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.MANAGE_CRM_ACCOUNT
    ]
  }
]

// Publishes the built-in role templates that local and platform environments should always be able to bootstrap.
export const BUILT_IN_ROLE_TEMPLATES: BuiltInRoleTemplateSeed[] = [
  {
    id: '2cf72f72-e04a-4946-b8c0-22f120f82001',
    code: 'tenant.admin',
    name: '租户管理员',
    description: 'Built-in tenant administrator template for tenant governance bootstrap.',
    allowTenantPermissionOverride: false,
    isEnabled: true,
    isProtected: true,
    kind: RoleKind.SYSTEM_TEMPLATE,
    scopeKey: '__SYSTEM_TEMPLATE__',
    templateRoleCode: null,
    tenantId: null,
    permissionCodes: [
      ROLE_TEMPLATE_PERMISSION_CODES.LIST,
      ROLE_TEMPLATE_PERMISSION_CODES.GET_BY_ID,
      ROLE_INSTANCE_PERMISSION_CODES.CREATE,
      ROLE_INSTANCE_PERMISSION_CODES.CREATE_FROM_TEMPLATE,
      ROLE_INSTANCE_PERMISSION_CODES.UPDATE,
      ROLE_INSTANCE_PERMISSION_CODES.DELETE,
      ROLE_INSTANCE_PERMISSION_CODES.ASSIGN_PERMISSIONS,
      ROLE_INSTANCE_PERMISSION_CODES.SYNC_FROM_TEMPLATE,
      ROLE_INSTANCE_PERMISSION_CODES.LIST,
      ROLE_INSTANCE_PERMISSION_CODES.GET_BY_ID,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_PERMISSION,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_NAVIGATION_ENTRY,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_ACCOUNT_ROLE,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_TERMINAL_ACCESS,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.MANAGE_ROLE_TERMINAL_ACCESS,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.MANAGE_ACCOUNT_TERMINAL_ACCESS,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.SET_ACCOUNT_ROLES,
      IDENTITY_ACCOUNT_PERMISSION_CODES.LIST_ACCOUNT,
      IDENTITY_ACCOUNT_PERMISSION_CODES.CREATE_ACCOUNT,
      IDENTITY_ACCOUNT_PERMISSION_CODES.UPDATE_ACCOUNT_PROFILE,
      IDENTITY_ACCOUNT_PERMISSION_CODES.UPDATE_ACCOUNT_STATUS,
      AUTH_SESSION_PERMISSION_CODES.ADMIN_VIEW_USER_SESSIONS,
      AUTH_SESSION_PERMISSION_CODES.ADMIN_REVOKE_SESSION,
      AUTH_MANAGEMENT_PERMISSION_CODES.BOOTSTRAP_ACCOUNT_CREDENTIALS,
      AUTH_MANAGEMENT_PERMISSION_CODES.MANAGE_ACCOUNT_LOGIN_METHODS,
      AUTH_MANAGEMENT_PERMISSION_CODES.MANAGE_TENANT_MFA_POLICY,
      CRM_MANAGEMENT_PERMISSION_CODES.READ_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.CREATE_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.UPDATE_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.CONVERT_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.CLAIM_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.RELEASE_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.MANAGE_CRM_ACCOUNT,
      TENANT_ORG_MANAGEMENT_PERMISSION_CODES.LIST_ORG_TREE,
      TENANT_ORG_MANAGEMENT_PERMISSION_CODES.VIEW_ORG_UNIT_DETAIL,
      TENANT_ORG_MANAGEMENT_PERMISSION_CODES.CREATE_ORG_UNIT,
      TENANT_ORG_MANAGEMENT_PERMISSION_CODES.UPDATE_ORG_UNIT,
      TENANT_ORG_MANAGEMENT_PERMISSION_CODES.ARCHIVE_ORG_UNIT,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.CREATE_ENROLLMENT,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.REVOKE_ENROLLMENT,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.READ_DEVICE,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.READ_SENSITIVE_DEVICE,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.DISABLE_DEVICE,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.MARK_LOST_DEVICE,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.MARK_MAINTENANCE_DEVICE,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.RESTORE_ACTIVE_DEVICE,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.MANAGE_VERSION_POLICY,
      TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.READ_AUDIT,
      PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES.READ,
      PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES.CREATE,
      PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES.UPDATE,
      PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES.DISABLE,
      PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES.ARCHIVE,
      PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES.STATS_READ,
      PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES.READ,
      PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES.MANAGE,
      PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES.ENABLE,
      PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES.DISABLE,
      PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES.PUBLIC_ENTRY_MANAGE,
      PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES.STATS_READ,
      SITE_MANAGEMENT_PERMISSION_CODES.READ,
      SITE_MANAGEMENT_PERMISSION_CODES.MANAGE,
      SITE_MANAGEMENT_PERMISSION_CODES.LOCALE_MANAGE,
      SITE_MANAGEMENT_PERMISSION_CODES.PRODUCT_MANAGE,
      SITE_MANAGEMENT_PERMISSION_CODES.CONTENT_MANAGE,
      SITE_MANAGEMENT_PERMISSION_CODES.SYNC,
      SITE_MANAGEMENT_PERMISSION_CODES.CREDENTIAL_MANAGE,
      SITE_MANAGEMENT_PERMISSION_CODES.AUDIT_READ,
      SITE_MANAGEMENT_PERMISSION_CODES.PREVIEW,
      BROWSER_ACTIVITY_AUDIT_PERMISSION_CODES.POLICY_READ,
      BROWSER_ACTIVITY_AUDIT_PERMISSION_CODES.POLICY_MANAGE,
      BROWSER_ACTIVITY_AUDIT_PERMISSION_CODES.OVERVIEW_READ,
      BROWSER_ACTIVITY_AUDIT_PERMISSION_CODES.EMPLOYEE_DETAIL_READ,
      BROWSER_ACTIVITY_AUDIT_PERMISSION_CODES.URL_DETAIL_READ,
      COLLABORATION_TASK_PERMISSION_CODES.CREATE,
      COLLABORATION_TASK_PERMISSION_CODES.ASSIGN
    ]
  },
  {
    id: '2cf72f72-e04a-4946-b8c0-22f120f82002',
    code: 'hr.admin',
    name: 'HR 管理员',
    description: 'Built-in HR administrator template for tenant employee onboarding.',
    allowTenantPermissionOverride: true,
    isEnabled: true,
    isProtected: false,
    kind: RoleKind.SYSTEM_TEMPLATE,
    scopeKey: '__SYSTEM_TEMPLATE__',
    templateRoleCode: null,
    tenantId: null,
    permissionCodes: [
      HR_MANAGEMENT_PERMISSION_CODES.LIST_EMPLOYEE,
      HR_MANAGEMENT_PERMISSION_CODES.VIEW_EMPLOYEE_DETAIL,
      HR_MANAGEMENT_PERMISSION_CODES.CREATE_EMPLOYEE,
      HR_MANAGEMENT_PERMISSION_CODES.CREATE_EMPLOYMENT,
      HR_MANAGEMENT_PERMISSION_CODES.END_EMPLOYMENT,
      HR_MANAGEMENT_PERMISSION_CODES.CHANGE_PRIMARY_EMPLOYMENT,
      IDENTITY_ACCOUNT_PERMISSION_CODES.LIST_ACCOUNT,
      IDENTITY_ACCOUNT_PERMISSION_CODES.CREATE_ACCOUNT,
      IDENTITY_ACCOUNT_PERMISSION_CODES.UPDATE_ACCOUNT_PROFILE,
      IDENTITY_ACCOUNT_PERMISSION_CODES.UPDATE_ACCOUNT_STATUS,
      IDENTITY_ACCOUNT_PERMISSION_CODES.ASSIGN_WORK_EMAIL,
      IDENTITY_ACCOUNT_PERMISSION_CODES.REVOKE_WORK_EMAIL,
      IDENTITY_ACCOUNT_PERMISSION_CODES.SET_PRIMARY_WORK_EMAIL,
      IDENTITY_ACCOUNT_PERMISSION_CODES.SET_WORK_EMAIL_STATUS,
      IDENTITY_ACCOUNT_PERMISSION_CODES.ASSIGN_WORK_PHONE,
      IDENTITY_ACCOUNT_PERMISSION_CODES.REVOKE_WORK_PHONE,
      IDENTITY_ACCOUNT_PERMISSION_CODES.SET_PRIMARY_WORK_PHONE,
      IDENTITY_ACCOUNT_PERMISSION_CODES.SET_WORK_PHONE_STATUS,
      AUTH_MANAGEMENT_PERMISSION_CODES.BOOTSTRAP_ACCOUNT_CREDENTIALS,
      AUTH_MANAGEMENT_PERMISSION_CODES.MANAGE_ACCOUNT_LOGIN_METHODS,
      AUTH_SESSION_PERMISSION_CODES.ADMIN_REVOKE_SESSION,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_ACCOUNT_ROLE
    ]
  },
  {
    id: '2cf72f72-e04a-4946-b8c0-22f120f82003',
    code: 'account.basic',
    name: '基础账号',
    description: 'Built-in minimum access template for login-capable tenant accounts.',
    allowTenantPermissionOverride: false,
    isEnabled: true,
    isProtected: true,
    kind: RoleKind.SYSTEM_TEMPLATE,
    scopeKey: '__SYSTEM_TEMPLATE__',
    templateRoleCode: null,
    tenantId: null,
    permissionCodes: [
      IDENTITY_ACCOUNT_SELF_PERMISSION_CODES.READ,
      TENANT_ORG_MANAGEMENT_PERMISSION_CODES.LIST_ORG_TREE,
      TENANT_ORG_MANAGEMENT_PERMISSION_CODES.VIEW_ORG_UNIT_DETAIL
    ]
  },
  {
    id: '2cf72f72-e04a-4946-b8c0-22f120f82004',
    code: 'mes.forming_workshop.supervisor',
    name: '成型车间主管',
    description:
      'Built-in MES forming workshop supervisor template for the mold management minimum loop.',
    allowTenantPermissionOverride: true,
    isEnabled: true,
    isProtected: false,
    kind: RoleKind.SYSTEM_TEMPLATE,
    scopeKey: '__SYSTEM_TEMPLATE__',
    templateRoleCode: null,
    tenantId: null,
    permissionCodes: [
      MES_MANAGEMENT_PERMISSION_CODES.READ_PRODUCTION_SPEC,
      MES_MANAGEMENT_PERMISSION_CODES.MANAGE_PRODUCTION_SPEC,
      MES_MANAGEMENT_PERMISSION_CODES.READ_MOLD_DESIGN,
      MES_MANAGEMENT_PERMISSION_CODES.MANAGE_MOLD_DESIGN,
      MES_MANAGEMENT_PERMISSION_CODES.READ_PRODUCTION_MOLD,
      MES_MANAGEMENT_PERMISSION_CODES.MANAGE_PRODUCTION_MOLD,
      MES_MANAGEMENT_PERMISSION_CODES.READ_TOOLING_INSTALLATION,
      MES_MANAGEMENT_PERMISSION_CODES.MANAGE_TOOLING_INSTALLATION,
      MES_MANAGEMENT_PERMISSION_CODES.RECORD_MOLD_USAGE,
      MES_MANAGEMENT_PERMISSION_CODES.MANAGE_MOLD_LIFE
    ]
  },
  {
    id: '2cf72f72-e04a-4946-b8c0-22f120f82005',
    code: 'item_master.product_data_manager',
    name: 'Item 主数据管理员',
    description:
      'Built-in Item product data manager template for tenant product master data maintenance.',
    allowTenantPermissionOverride: true,
    isEnabled: true,
    isProtected: false,
    kind: RoleKind.SYSTEM_TEMPLATE,
    scopeKey: '__SYSTEM_TEMPLATE__',
    templateRoleCode: null,
    tenantId: null,
    permissionCodes: [
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.LIST_ITEM_MODEL,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.VIEW_ITEM_MODEL_DETAIL,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.CREATE_ITEM_MODEL,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.MANAGE_ITEM_MODEL,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.LIST_ITEM,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.VIEW_ITEM_DETAIL,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.CREATE_ITEM,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.UPDATE_ITEM_BASICS,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.UPDATE_ITEM_STATUS,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.SET_ITEM_PRIMARY_CATEGORY,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.LIST_ITEM_CATEGORIES,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.CREATE_ITEM_CATEGORY,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.UPDATE_ITEM_CATEGORY_BASICS,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.UPDATE_ITEM_CATEGORY_STATUS,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.DELETE_ITEM_CATEGORY,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.LIST_ATTRIBUTE,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.CREATE_ATTRIBUTE,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.MANAGE_ATTRIBUTE,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.LIST_PACKAGING,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.CREATE_PACKAGING,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.MANAGE_PACKAGING,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.LIST_BOM,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.CREATE_BOM,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.MANAGE_BOM,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.SET_ITEM_CAPABILITIES,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.LIST_SUPPLIER_ITEM_MAPPINGS,
      ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.UPSERT_SUPPLIER_ITEM_MAPPING
    ]
  },
  {
    id: '2cf72f72-e04a-4946-b8c0-22f120f82006',
    code: 'extension.designer',
    name: '插件设计师',
    description:
      'Built-in browser extension designer template for the product discovery demo loop.',
    allowTenantPermissionOverride: true,
    isEnabled: true,
    isProtected: false,
    kind: RoleKind.SYSTEM_TEMPLATE,
    scopeKey: '__SYSTEM_TEMPLATE__',
    templateRoleCode: null,
    tenantId: null,
    permissionCodes: []
  },
  {
    id: '2cf72f72-e04a-4946-b8c0-22f120f82007',
    code: 'crm.sales',
    name: 'CRM 销售',
    description: 'Built-in CRM sales template for account execution and daily customer follow-up.',
    allowTenantPermissionOverride: true,
    isEnabled: true,
    isProtected: false,
    kind: RoleKind.SYSTEM_TEMPLATE,
    scopeKey: '__SYSTEM_TEMPLATE__',
    templateRoleCode: null,
    tenantId: null,
    permissionCodes: [
      CRM_MANAGEMENT_PERMISSION_CODES.READ_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.CREATE_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.UPDATE_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.CLAIM_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.RELEASE_CRM_ACCOUNT
    ]
  },
  {
    id: '2cf72f72-e04a-4946-b8c0-22f120f82008',
    code: 'crm.sales_manager',
    name: 'CRM 销售主管',
    description:
      'Built-in CRM sales manager template for team account governance and pipeline management.',
    allowTenantPermissionOverride: true,
    isEnabled: true,
    isProtected: false,
    kind: RoleKind.SYSTEM_TEMPLATE,
    scopeKey: '__SYSTEM_TEMPLATE__',
    templateRoleCode: null,
    tenantId: null,
    permissionCodes: [
      CRM_MANAGEMENT_PERMISSION_CODES.READ_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.CREATE_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.UPDATE_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.CLAIM_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.RELEASE_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.CONVERT_CRM_ACCOUNT,
      CRM_MANAGEMENT_PERMISSION_CODES.MANAGE_CRM_ACCOUNT
    ]
  }
]

/** buildBuiltInRoleSeeds returns the complete built-in role seed set without writing to a database. */
export function buildBuiltInRoleSeeds(): BuiltInRoleSeed[] {
  return [...BUILT_IN_SYSTEM_ROLES, ...BUILT_IN_ROLE_TEMPLATES]
}

/** validateBuiltInRoleSeedDefinitions checks role seed consistency before any DB writer consumes it. */
export function validateBuiltInRoleSeedDefinitions(): string[] {
  const errors: string[] = []
  const permissionByCode = new Map(PERMISSION_CODE_SEED_ITEMS.map((item) => [item.code, item]))
  const seenRoleKeys = new Set<string>()

  for (const role of buildBuiltInRoleSeeds()) {
    const roleKey = `${role.scopeKey}:${role.kind}:${role.code}`
    if (seenRoleKeys.has(roleKey)) {
      errors.push(`Duplicate role seed key: ${roleKey}`)
    }
    seenRoleKeys.add(roleKey)

    if (role.isProtected && role.allowTenantPermissionOverride) {
      errors.push(`${role.code}: protected role cannot allow tenant permission override`)
    }

    if (role.kind === RoleKind.SYSTEM_INSTANCE) {
      if (role.scopeKey !== '__SYSTEM__') {
        errors.push(`${role.code}: SYSTEM_INSTANCE must use scopeKey __SYSTEM__`)
      }
      if (role.tenantId !== null || role.templateRoleCode !== null) {
        errors.push(`${role.code}: SYSTEM_INSTANCE must not set tenantId or templateRoleCode`)
      }
    }

    if (role.kind === RoleKind.SYSTEM_TEMPLATE) {
      if (role.scopeKey !== '__SYSTEM_TEMPLATE__') {
        errors.push(`${role.code}: SYSTEM_TEMPLATE must use scopeKey __SYSTEM_TEMPLATE__`)
      }
      if (role.tenantId !== null || role.templateRoleCode !== null) {
        errors.push(`${role.code}: SYSTEM_TEMPLATE must not set tenantId or templateRoleCode`)
      }
    }

    if (role.kind === RoleKind.TENANT_INSTANCE) {
      if (!role.tenantId) {
        errors.push(`${role.code}: TENANT_INSTANCE must set tenantId`)
      }
      if (role.tenantId && role.scopeKey !== role.tenantId) {
        errors.push(`${role.code}: TENANT_INSTANCE scopeKey must equal tenantId`)
      }
    }

    const seenPermissionCodes = new Set<string>()
    for (const permissionCode of role.permissionCodes) {
      if (seenPermissionCodes.has(permissionCode)) {
        errors.push(`${role.code}: duplicate permission code ${permissionCode}`)
      }
      seenPermissionCodes.add(permissionCode)

      const permission = permissionByCode.get(permissionCode)
      if (!permission) {
        errors.push(`${role.code}: unknown permission code ${permissionCode}`)
      } else if (permission.kind === 'INTERNAL') {
        errors.push(
          `${role.code}: INTERNAL permission code ${permissionCode} cannot be granted to a role`
        )
      }
    }
  }

  return errors
}
