import {
  AUTH_MANAGEMENT_PERMISSION_CODES,
  AUTH_SESSION_PERMISSION_CODES,
  BROWSER_ACTIVITY_AUDIT_PERMISSION_CODES,
  COLLABORATION_TASK_PERMISSION_CODES,
  CRM_MANAGEMENT_PERMISSION_CODES,
  HR_MANAGEMENT_PERMISSION_CODES,
  IDENTITY_ACCOUNT_PERMISSION_CODES,
  IDENTITY_ACCOUNT_SELF_PERMISSION_CODES,
  IDENTITY_MACHINE_PERMISSION_CODES,
  ITEM_MASTER_MANAGEMENT_PERMISSION_CODES,
  PERMISSION_MANAGEMENT_PERMISSION_CODES,
  PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES,
  PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES,
  ROLE_INSTANCE_PERMISSION_CODES,
  ROLE_TEMPLATE_PERMISSION_CODES,
  SITE_MANAGEMENT_PERMISSION_CODES,
  TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES,
  TENANT_ORG_MANAGEMENT_PERMISSION_CODES
} from '../scripts/permission-catalog'
import {
  BUILT_IN_ROLE_TEMPLATES,
  BUILT_IN_SYSTEM_ROLES,
  validateBuiltInRoleSeedDefinitions
} from '../scripts/role-foundation'
import { RoleKind } from '../../prisma/generated/prisma'

// Verifies the built-in role foundation separates protected platform roles from tenant-governed roles.
describe('role foundation seed', () => {
  it('publishes complete and valid built-in role seed definitions', () => {
    expect(validateBuiltInRoleSeedDefinitions()).toEqual([])
  })

  it('publishes the built-in system admin instance baseline with platform and CRM governance permissions', () => {
    expect(BUILT_IN_SYSTEM_ROLES).toEqual([
      {
        code: 'system.admin',
        description: 'Built-in system administrator role for platform-level governance.',
        id: '37e76049-6d90-456c-8ded-2cc42c60f001',
        isEnabled: true,
        kind: RoleKind.SYSTEM_INSTANCE,
        name: '系统管理员',
        allowTenantPermissionOverride: false,
        isProtected: true,
        scopeKey: '__SYSTEM__',
        templateRoleCode: null,
        tenantId: null,
        permissionCodes: [
          PERMISSION_MANAGEMENT_PERMISSION_CODES.CREATE_PERMISSION,
          PERMISSION_MANAGEMENT_PERMISSION_CODES.UPDATE_PERMISSION,
          PERMISSION_MANAGEMENT_PERMISSION_CODES.DELETE_PERMISSION,
          PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_PERMISSION,
          PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_PERMISSION_DETAIL,
          PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_PERMISSION_DETAIL_BY_CODE,
          PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_AUDIT_EVENT,
          PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_NAVIGATION_ENTRY,
          PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_NAVIGATION_ENTRY_DETAIL,
          PERMISSION_MANAGEMENT_PERMISSION_CODES.CREATE_NAVIGATION_ENTRY,
          PERMISSION_MANAGEMENT_PERMISSION_CODES.UPDATE_NAVIGATION_ENTRY,
          PERMISSION_MANAGEMENT_PERMISSION_CODES.RESOLVE_NAVIGATION_PREVIEW,
          PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_TERMINAL_ACCESS,
          PERMISSION_MANAGEMENT_PERMISSION_CODES.MANAGE_ROLE_TERMINAL_ACCESS,
          PERMISSION_MANAGEMENT_PERMISSION_CODES.MANAGE_ACCOUNT_TERMINAL_ACCESS,
          ROLE_TEMPLATE_PERMISSION_CODES.CREATE,
          ROLE_TEMPLATE_PERMISSION_CODES.UPDATE,
          ROLE_TEMPLATE_PERMISSION_CODES.DELETE,
          ROLE_TEMPLATE_PERMISSION_CODES.ASSIGN_PERMISSIONS,
          ROLE_TEMPLATE_PERMISSION_CODES.LIST,
          ROLE_TEMPLATE_PERMISSION_CODES.GET_BY_ID,
          ROLE_INSTANCE_PERMISSION_CODES.CREATE,
          ROLE_INSTANCE_PERMISSION_CODES.CREATE_FROM_TEMPLATE,
          ROLE_INSTANCE_PERMISSION_CODES.UPDATE,
          ROLE_INSTANCE_PERMISSION_CODES.DELETE,
          ROLE_INSTANCE_PERMISSION_CODES.ASSIGN_PERMISSIONS,
          ROLE_INSTANCE_PERMISSION_CODES.SYNC_FROM_TEMPLATE,
          ROLE_INSTANCE_PERMISSION_CODES.LIST,
          ROLE_INSTANCE_PERMISSION_CODES.GET_BY_ID,
          PERMISSION_MANAGEMENT_PERMISSION_CODES.ASSIGN_ACCOUNT_ROLE,
          PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_ACCOUNT_ROLE,
          PERMISSION_MANAGEMENT_PERMISSION_CODES.CREATE_POLICY,
          PERMISSION_MANAGEMENT_PERMISSION_CODES.UPDATE_POLICY,
          PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_POLICY,
          AUTH_SESSION_PERMISSION_CODES.ADMIN_VIEW_USER_SESSIONS,
          AUTH_SESSION_PERMISSION_CODES.ADMIN_REVOKE_SESSION,
          AUTH_MANAGEMENT_PERMISSION_CODES.VIEW_AUDIT_EVENT,
          AUTH_MANAGEMENT_PERMISSION_CODES.BOOTSTRAP_ACCOUNT_CREDENTIALS,
          AUTH_MANAGEMENT_PERMISSION_CODES.MANAGE_ACCOUNT_LOGIN_METHODS,
          AUTH_MANAGEMENT_PERMISSION_CODES.MANAGE_PLATFORM_MFA_POLICY,
          IDENTITY_ACCOUNT_PERMISSION_CODES.LIST_ACCOUNT,
          IDENTITY_ACCOUNT_PERMISSION_CODES.CREATE_ACCOUNT,
          IDENTITY_ACCOUNT_PERMISSION_CODES.UPDATE_ACCOUNT_PROFILE,
          IDENTITY_ACCOUNT_PERMISSION_CODES.UPDATE_ACCOUNT_STATUS,
          IDENTITY_ACCOUNT_PERMISSION_CODES.DELETE_ACCOUNT,
          IDENTITY_ACCOUNT_SELF_PERMISSION_CODES.READ,
          IDENTITY_MACHINE_PERMISSION_CODES.CREATE_SERVICE_ACCOUNT,
          IDENTITY_MACHINE_PERMISSION_CODES.UPDATE_SERVICE_ACCOUNT_STATUS,
          IDENTITY_MACHINE_PERMISSION_CODES.CREATE_API_KEY,
          IDENTITY_MACHINE_PERMISSION_CODES.REVOKE_API_KEY,
          IDENTITY_MACHINE_PERMISSION_CODES.ROTATE_API_KEY,
          TENANT_ORG_MANAGEMENT_PERMISSION_CODES.LIST_TENANT,
          TENANT_ORG_MANAGEMENT_PERMISSION_CODES.VIEW_TENANT_DETAIL,
          TENANT_ORG_MANAGEMENT_PERMISSION_CODES.CREATE_TENANT,
          TENANT_ORG_MANAGEMENT_PERMISSION_CODES.UPDATE_TENANT_PROFILE,
          TENANT_ORG_MANAGEMENT_PERMISSION_CODES.UPDATE_TENANT_STATUS,
          TENANT_ORG_MANAGEMENT_PERMISSION_CODES.LIST_ORG_TREE,
          TENANT_ORG_MANAGEMENT_PERMISSION_CODES.VIEW_ORG_UNIT_DETAIL,
          TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.CREATE_ENROLLMENT,
          TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.REVOKE_ENROLLMENT,
          TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.READ_DEVICE,
          TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.READ_SENSITIVE_DEVICE,
          TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.DISABLE_DEVICE,
          TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.MARK_LOST_DEVICE,
          TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.MARK_MAINTENANCE_DEVICE,
          TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.RESTORE_ACTIVE_DEVICE,
          TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.MANAGE_VERSION_POLICY,
          TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.READ_AUDIT,
          CRM_MANAGEMENT_PERMISSION_CODES.READ_CRM_ACCOUNT,
          CRM_MANAGEMENT_PERMISSION_CODES.CREATE_CRM_ACCOUNT,
          CRM_MANAGEMENT_PERMISSION_CODES.UPDATE_CRM_ACCOUNT,
          CRM_MANAGEMENT_PERMISSION_CODES.CONVERT_CRM_ACCOUNT,
          CRM_MANAGEMENT_PERMISSION_CODES.CLAIM_CRM_ACCOUNT,
          CRM_MANAGEMENT_PERMISSION_CODES.RELEASE_CRM_ACCOUNT,
          CRM_MANAGEMENT_PERMISSION_CODES.MANAGE_CRM_ACCOUNT
        ]
      }
    ])
  })

  it('publishes the built-in tenant admin template baseline', () => {
    expect(BUILT_IN_ROLE_TEMPLATES).toContainEqual({
      code: 'tenant.admin',
      description: 'Built-in tenant administrator template for tenant governance bootstrap.',
      id: '2cf72f72-e04a-4946-b8c0-22f120f82001',
      isEnabled: true,
      kind: RoleKind.SYSTEM_TEMPLATE,
      name: '租户管理员',
      allowTenantPermissionOverride: false,
      isProtected: true,
      scopeKey: '__SYSTEM_TEMPLATE__',
      templateRoleCode: null,
      tenantId: null,
      permissionCodes: [
        ROLE_TEMPLATE_PERMISSION_CODES.LIST,
        ROLE_TEMPLATE_PERMISSION_CODES.GET_BY_ID,
        ROLE_INSTANCE_PERMISSION_CODES.CREATE,
        ROLE_INSTANCE_PERMISSION_CODES.CREATE_FROM_TEMPLATE,
        ROLE_INSTANCE_PERMISSION_CODES.UPDATE,
        ROLE_INSTANCE_PERMISSION_CODES.DELETE,
        ROLE_INSTANCE_PERMISSION_CODES.ASSIGN_PERMISSIONS,
        ROLE_INSTANCE_PERMISSION_CODES.SYNC_FROM_TEMPLATE,
        ROLE_INSTANCE_PERMISSION_CODES.LIST,
        ROLE_INSTANCE_PERMISSION_CODES.GET_BY_ID,
        PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_PERMISSION,
        PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_NAVIGATION_ENTRY,
        PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_ACCOUNT_ROLE,
        PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_TERMINAL_ACCESS,
        PERMISSION_MANAGEMENT_PERMISSION_CODES.MANAGE_ROLE_TERMINAL_ACCESS,
        PERMISSION_MANAGEMENT_PERMISSION_CODES.MANAGE_ACCOUNT_TERMINAL_ACCESS,
        PERMISSION_MANAGEMENT_PERMISSION_CODES.SET_ACCOUNT_ROLES,
        IDENTITY_ACCOUNT_PERMISSION_CODES.LIST_ACCOUNT,
        IDENTITY_ACCOUNT_PERMISSION_CODES.CREATE_ACCOUNT,
        IDENTITY_ACCOUNT_PERMISSION_CODES.UPDATE_ACCOUNT_PROFILE,
        IDENTITY_ACCOUNT_PERMISSION_CODES.UPDATE_ACCOUNT_STATUS,
        AUTH_SESSION_PERMISSION_CODES.ADMIN_VIEW_USER_SESSIONS,
        AUTH_SESSION_PERMISSION_CODES.ADMIN_REVOKE_SESSION,
        AUTH_MANAGEMENT_PERMISSION_CODES.BOOTSTRAP_ACCOUNT_CREDENTIALS,
        AUTH_MANAGEMENT_PERMISSION_CODES.MANAGE_ACCOUNT_LOGIN_METHODS,
        AUTH_MANAGEMENT_PERMISSION_CODES.MANAGE_TENANT_MFA_POLICY,
        CRM_MANAGEMENT_PERMISSION_CODES.READ_CRM_ACCOUNT,
        CRM_MANAGEMENT_PERMISSION_CODES.CREATE_CRM_ACCOUNT,
        CRM_MANAGEMENT_PERMISSION_CODES.UPDATE_CRM_ACCOUNT,
        CRM_MANAGEMENT_PERMISSION_CODES.CONVERT_CRM_ACCOUNT,
        CRM_MANAGEMENT_PERMISSION_CODES.CLAIM_CRM_ACCOUNT,
        CRM_MANAGEMENT_PERMISSION_CODES.RELEASE_CRM_ACCOUNT,
        CRM_MANAGEMENT_PERMISSION_CODES.MANAGE_CRM_ACCOUNT,
        TENANT_ORG_MANAGEMENT_PERMISSION_CODES.LIST_ORG_TREE,
        TENANT_ORG_MANAGEMENT_PERMISSION_CODES.VIEW_ORG_UNIT_DETAIL,
        TENANT_ORG_MANAGEMENT_PERMISSION_CODES.CREATE_ORG_UNIT,
        TENANT_ORG_MANAGEMENT_PERMISSION_CODES.UPDATE_ORG_UNIT,
        TENANT_ORG_MANAGEMENT_PERMISSION_CODES.ARCHIVE_ORG_UNIT,
        TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.CREATE_ENROLLMENT,
        TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.REVOKE_ENROLLMENT,
        TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.READ_DEVICE,
        TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.READ_SENSITIVE_DEVICE,
        TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.DISABLE_DEVICE,
        TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.MARK_LOST_DEVICE,
        TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.MARK_MAINTENANCE_DEVICE,
        TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.RESTORE_ACTIVE_DEVICE,
        TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.MANAGE_VERSION_POLICY,
        TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES.READ_AUDIT,
        PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES.READ,
        PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES.CREATE,
        PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES.UPDATE,
        PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES.DISABLE,
        PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES.ARCHIVE,
        PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES.STATS_READ,
        PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES.READ,
        PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES.MANAGE,
        PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES.ENABLE,
        PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES.DISABLE,
        PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES.PUBLIC_ENTRY_MANAGE,
        PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES.STATS_READ,
        SITE_MANAGEMENT_PERMISSION_CODES.READ,
        SITE_MANAGEMENT_PERMISSION_CODES.MANAGE,
        SITE_MANAGEMENT_PERMISSION_CODES.LOCALE_MANAGE,
        SITE_MANAGEMENT_PERMISSION_CODES.PRODUCT_MANAGE,
        SITE_MANAGEMENT_PERMISSION_CODES.CONTENT_MANAGE,
        SITE_MANAGEMENT_PERMISSION_CODES.SYNC,
        SITE_MANAGEMENT_PERMISSION_CODES.CREDENTIAL_MANAGE,
        SITE_MANAGEMENT_PERMISSION_CODES.AUDIT_READ,
        SITE_MANAGEMENT_PERMISSION_CODES.PREVIEW,
        BROWSER_ACTIVITY_AUDIT_PERMISSION_CODES.POLICY_READ,
        BROWSER_ACTIVITY_AUDIT_PERMISSION_CODES.POLICY_MANAGE,
        BROWSER_ACTIVITY_AUDIT_PERMISSION_CODES.OVERVIEW_READ,
        BROWSER_ACTIVITY_AUDIT_PERMISSION_CODES.EMPLOYEE_DETAIL_READ,
        BROWSER_ACTIVITY_AUDIT_PERMISSION_CODES.URL_DETAIL_READ,
        COLLABORATION_TASK_PERMISSION_CODES.CREATE,
        COLLABORATION_TASK_PERMISSION_CODES.ASSIGN
      ]
    })
  })

  it('publishes the built-in HR admin template baseline', () => {
    expect(BUILT_IN_ROLE_TEMPLATES).toContainEqual({
      code: 'hr.admin',
      description: 'Built-in HR administrator template for tenant employee onboarding.',
      id: '2cf72f72-e04a-4946-b8c0-22f120f82002',
      isEnabled: true,
      kind: RoleKind.SYSTEM_TEMPLATE,
      name: 'HR 管理员',
      allowTenantPermissionOverride: true,
      isProtected: false,
      scopeKey: '__SYSTEM_TEMPLATE__',
      templateRoleCode: null,
      tenantId: null,
      permissionCodes: [
        HR_MANAGEMENT_PERMISSION_CODES.LIST_EMPLOYEE,
        HR_MANAGEMENT_PERMISSION_CODES.VIEW_EMPLOYEE_DETAIL,
        HR_MANAGEMENT_PERMISSION_CODES.CREATE_EMPLOYEE,
        HR_MANAGEMENT_PERMISSION_CODES.CREATE_EMPLOYMENT,
        HR_MANAGEMENT_PERMISSION_CODES.END_EMPLOYMENT,
        HR_MANAGEMENT_PERMISSION_CODES.CHANGE_PRIMARY_EMPLOYMENT,
        IDENTITY_ACCOUNT_PERMISSION_CODES.LIST_ACCOUNT,
        IDENTITY_ACCOUNT_PERMISSION_CODES.CREATE_ACCOUNT,
        IDENTITY_ACCOUNT_PERMISSION_CODES.UPDATE_ACCOUNT_PROFILE,
        IDENTITY_ACCOUNT_PERMISSION_CODES.UPDATE_ACCOUNT_STATUS,
        IDENTITY_ACCOUNT_PERMISSION_CODES.ASSIGN_WORK_EMAIL,
        IDENTITY_ACCOUNT_PERMISSION_CODES.REVOKE_WORK_EMAIL,
        IDENTITY_ACCOUNT_PERMISSION_CODES.SET_PRIMARY_WORK_EMAIL,
        IDENTITY_ACCOUNT_PERMISSION_CODES.SET_WORK_EMAIL_STATUS,
        IDENTITY_ACCOUNT_PERMISSION_CODES.ASSIGN_WORK_PHONE,
        IDENTITY_ACCOUNT_PERMISSION_CODES.REVOKE_WORK_PHONE,
        IDENTITY_ACCOUNT_PERMISSION_CODES.SET_PRIMARY_WORK_PHONE,
        IDENTITY_ACCOUNT_PERMISSION_CODES.SET_WORK_PHONE_STATUS,
        AUTH_MANAGEMENT_PERMISSION_CODES.BOOTSTRAP_ACCOUNT_CREDENTIALS,
        AUTH_MANAGEMENT_PERMISSION_CODES.MANAGE_ACCOUNT_LOGIN_METHODS,
        AUTH_SESSION_PERMISSION_CODES.ADMIN_REVOKE_SESSION,
        PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_ACCOUNT_ROLE
      ]
    })
  })

  it('publishes the built-in account basic template baseline', () => {
    expect(BUILT_IN_ROLE_TEMPLATES).toContainEqual({
      code: 'account.basic',
      description: 'Built-in minimum access template for login-capable tenant accounts.',
      id: '2cf72f72-e04a-4946-b8c0-22f120f82003',
      isEnabled: true,
      kind: RoleKind.SYSTEM_TEMPLATE,
      name: '基础账号',
      allowTenantPermissionOverride: false,
      isProtected: true,
      scopeKey: '__SYSTEM_TEMPLATE__',
      templateRoleCode: null,
      tenantId: null,
      permissionCodes: [
        IDENTITY_ACCOUNT_SELF_PERMISSION_CODES.READ,
        TENANT_ORG_MANAGEMENT_PERMISSION_CODES.LIST_ORG_TREE,
        TENANT_ORG_MANAGEMENT_PERMISSION_CODES.VIEW_ORG_UNIT_DETAIL
      ]
    })
  })

  it('publishes the built-in CRM role templates for sales execution and sales management', () => {
    expect(BUILT_IN_ROLE_TEMPLATES).toContainEqual({
      code: 'crm.sales',
      description:
        'Built-in CRM sales template for account execution and daily customer follow-up.',
      id: '2cf72f72-e04a-4946-b8c0-22f120f82007',
      isEnabled: true,
      kind: RoleKind.SYSTEM_TEMPLATE,
      name: 'CRM 销售',
      allowTenantPermissionOverride: true,
      isProtected: false,
      scopeKey: '__SYSTEM_TEMPLATE__',
      templateRoleCode: null,
      tenantId: null,
      permissionCodes: [
        CRM_MANAGEMENT_PERMISSION_CODES.READ_CRM_ACCOUNT,
        CRM_MANAGEMENT_PERMISSION_CODES.CREATE_CRM_ACCOUNT,
        CRM_MANAGEMENT_PERMISSION_CODES.UPDATE_CRM_ACCOUNT,
        CRM_MANAGEMENT_PERMISSION_CODES.CLAIM_CRM_ACCOUNT,
        CRM_MANAGEMENT_PERMISSION_CODES.RELEASE_CRM_ACCOUNT
      ]
    })

    expect(BUILT_IN_ROLE_TEMPLATES).toContainEqual({
      code: 'crm.sales_manager',
      description:
        'Built-in CRM sales manager template for team account governance and pipeline management.',
      id: '2cf72f72-e04a-4946-b8c0-22f120f82008',
      isEnabled: true,
      kind: RoleKind.SYSTEM_TEMPLATE,
      name: 'CRM 销售主管',
      allowTenantPermissionOverride: true,
      isProtected: false,
      scopeKey: '__SYSTEM_TEMPLATE__',
      templateRoleCode: null,
      tenantId: null,
      permissionCodes: [
        CRM_MANAGEMENT_PERMISSION_CODES.READ_CRM_ACCOUNT,
        CRM_MANAGEMENT_PERMISSION_CODES.CREATE_CRM_ACCOUNT,
        CRM_MANAGEMENT_PERMISSION_CODES.UPDATE_CRM_ACCOUNT,
        CRM_MANAGEMENT_PERMISSION_CODES.CLAIM_CRM_ACCOUNT,
        CRM_MANAGEMENT_PERMISSION_CODES.RELEASE_CRM_ACCOUNT,
        CRM_MANAGEMENT_PERMISSION_CODES.CONVERT_CRM_ACCOUNT,
        CRM_MANAGEMENT_PERMISSION_CODES.MANAGE_CRM_ACCOUNT
      ]
    })
  })

  it('publishes the built-in item product data manager template baseline', () => {
    expect(BUILT_IN_ROLE_TEMPLATES).toContainEqual({
      code: 'item_master.product_data_manager',
      description:
        'Built-in Item product data manager template for tenant product master data maintenance.',
      id: '2cf72f72-e04a-4946-b8c0-22f120f82005',
      isEnabled: true,
      kind: RoleKind.SYSTEM_TEMPLATE,
      name: 'Item 主数据管理员',
      allowTenantPermissionOverride: true,
      isProtected: false,
      scopeKey: '__SYSTEM_TEMPLATE__',
      templateRoleCode: null,
      tenantId: null,
      permissionCodes: [
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.LIST_ITEM_MODEL,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.VIEW_ITEM_MODEL_DETAIL,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.CREATE_ITEM_MODEL,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.MANAGE_ITEM_MODEL,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.LIST_ITEM,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.VIEW_ITEM_DETAIL,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.CREATE_ITEM,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.UPDATE_ITEM_BASICS,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.UPDATE_ITEM_STATUS,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.SET_ITEM_PRIMARY_CATEGORY,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.LIST_ITEM_CATEGORIES,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.CREATE_ITEM_CATEGORY,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.UPDATE_ITEM_CATEGORY_BASICS,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.UPDATE_ITEM_CATEGORY_STATUS,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.DELETE_ITEM_CATEGORY,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.LIST_ATTRIBUTE,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.CREATE_ATTRIBUTE,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.MANAGE_ATTRIBUTE,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.LIST_PACKAGING,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.CREATE_PACKAGING,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.MANAGE_PACKAGING,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.LIST_BOM,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.CREATE_BOM,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.MANAGE_BOM,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.SET_ITEM_CAPABILITIES,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.LIST_SUPPLIER_ITEM_MAPPINGS,
        ITEM_MASTER_MANAGEMENT_PERMISSION_CODES.UPSERT_SUPPLIER_ITEM_MAPPING
      ]
    })
  })

  it('grants ItemModel lifecycle permissions to the item product data manager template', () => {
    const productDataManager = BUILT_IN_ROLE_TEMPLATES.find(
      (role) => role.code === 'item_master.product_data_manager'
    )

    expect(productDataManager?.permissionCodes).toEqual(
      expect.arrayContaining([
        'item_master.item_model.list',
        'item_master.item_model.get_by_id',
        'item_master.item_model.create',
        'item_master.item_model.manage'
      ])
    )
  })

  it('grants Public Entry management permissions to the tenant admin template', () => {
    const tenantAdmin = BUILT_IN_ROLE_TEMPLATES.find((role) => role.code === 'tenant.admin')

    expect(tenantAdmin?.permissionCodes).toEqual(
      expect.arrayContaining([
        PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES.READ,
        PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES.CREATE,
        PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES.UPDATE,
        PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES.DISABLE,
        PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES.ARCHIVE,
        PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES.STATS_READ,
        PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES.READ,
        PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES.MANAGE,
        PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES.ENABLE,
        PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES.DISABLE,
        PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES.PUBLIC_ENTRY_MANAGE,
        PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES.STATS_READ
      ])
    )
  })
})
